name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up uv
        uses: astral-sh/setup-uv@v3
      - name: Install dependencies with uv
        run: |
          if [ -s requirements.txt ]; then uv pip install -r requirements.txt; fi
          uv pip install pytest
      - name: Run tests with uv
        run: uv run pytest -q
